language: rust
sudo: false
cache: cargo
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
       - FEATURES=nightly
       - BENCH=
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$TRAVIS_RUST_VERSION" == nightly* ] || (cargo install clippy && cargo clippy --verbose --features "$FEATURES")) &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")

