language: rust
sudo: false
cache: cargo
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
       - FEATURES=nightly
       - BENCH=
branches:
  only:
    - master
script:
  - |
      cargo install cargo-clippy &&
      ([ -z "$FEATURES" ] || cargo build --verbose --features "$FEATURES") &&
      ([ -z "$FEATURES" ] || cargo test --verbose --features "$FEATURES") &&
      ([ -z "$FEATURES" ] || cargo clippy --verbose --features "$FEATURES") &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")

